local addonName, Mute = ...;
Mute.L = {};
local L = Mute.L;

local LOCALE = GetLocale();

if LOCALE == "enUS" then
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE
	L["TOC_Notes"] = "Adds mute functions in the game similar to an expanded ignore system."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	--[[
	esMX silencio
	deDE stumm
	frFR muet
	itIT silenzia
	ptBR mudo
	ruRU молчать
	koKR 무음
	zhCN 禁音
	zhTW 消音
	]]
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/mutelist"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s is now being muted."
	L["Ignore_Removed"] = "%s is no longer being muted."
	L["Ignore_Added_Guild"] = "<%s> is now being muted."
	L["Ignore_Removed_Guild"] = "<%s> is no longer being muted."
	L["MutePlayer"] = "Mute Player"
	L["UnmutePlayer"] = "Unmute Player"
	L["MuteGuild"] = "Mute Guild"
	L["UnmuteGuild"] = "Unmute Guild"
	L["Watcher"] = "Watcher"
	L["NewEntry"] = "NEW (%s): %s [%s]%s"
	L["NewGuild"] = "NEW guild: "
	L["MuteList"] = "Mute List"
	L["MutedPlayers_Header"] = "Muted Players (%d)"
	L["MutedGuilds_Header"] = "Muted Guild (%d)"
	L["Watchlist_Header"] = "Watcher List (%d)"
	L["ExceptedGuilds_Header"] = "Excepted Guilds (%d)"
	L["MutedGuild"] = "Muted Guild"
	L["MutedViaGuild"] = "Muted via Guild: <%s>"
	L["UnmutedTheGuild"] = "(Unmuting will unmute the guild)"
	L["ExceptedViaGuild"] = "<%s> is an excepted guild"
	L["WatcherEntry"] = "Watcher entry (%s)"
	L["GuildEntry"] = "Guild: <%s>"
	L["SeenCount"] = "Seen %s times"
	L["LastSeen"] = "Last seen: %s"
	L["MutedManually"] = "Muted Manually"
	L["EnterEntryText"] = "Enter name of the player or guild to mute.\nor\nShift click a name from the chat window"
	L["NoMutedPlayers"] = "No muted players."
	L["HoldShiftToConfirm"] = "Hold Shift to Confirm"
	L["ListeningOnChannel"] = "listening on channel #%s (%s)"
	L["CouldntJoin"] = "could not join %s (password set, banned, or a sealed channel name)"
	L["Verified"] = "Verified"
	L["Addon"] = "Addon"
	L["Reported"] = "Reported"
	L["Suspected"] = "Suspected"
	L["Exception"] = "Exception (Not Muted)"
	L["WatcherGuild"] = "Watcher Guild"
	L["ExceptedGuild"] = "Excepted Guild"
	L["SeenPlayersNumber"] = "Seen %d players"
	L["PlayerIsMuted"] = "Player is muted"
	L["Guild_Exception_Added"] = "Guild exception added: %s"
	L["Guild_Exception_Removed"] = "Guild exception removed: %s"


	L["Setting_MuterHeader"] = "Muter"
	L["Setting_AddContextMenu"] = "Add Mute Context Menu"
	L["Setting_AddContextMenuTT"] = "Adds Mute / Unmute to the right-click menu of players."
	L["Setting_SpeechBubbles"] = "Affect Chat Bubbles"
	L["Setting_SpeechBubblesTT"] = "Toggle whether chat bubble text is obfuscated on muted characters."
	L["Setting_Chat_Notify"] = "Chat Notifications"
	L["Setting_Chat_NotifyTT"] = "Print a chat message when Watcher gathers a new entry."
	L["Setting_PauseWatcher"] = "Pause Watcher"
	L["Setting_PauseWatcherTT"] = "Pauses gathering new entries. Entries already gathered stay muted."
	L["Setting_UseNetwork"] = "Use Channel Network"
	L["Setting_UseNetworkTT"] = "Utilizes the OlympusNet channel to gather a mute list for Watcher.\nMutes will still be gathered via mouseover, /who info, nameplate, and other unit sources."

	L["Term_Contains"] = "Contains"
	L["Term_ContainsTT"] = "Matches anywhere in a message, even inside other words. \"gold\" also matches \"golden\"."
	L["Term_Word"] = "Word"
	L["Term_WordTT"] = "Matches only when the term stands by itself. \"gold\" matches \"selling gold\" but not \"golden\"."
	L["Term_ContainsAll"] = "Contains All"
	L["Term_ContainsAllTT"] = "Matches only if the message contains all specified terms (comma-separated)."
	L["Term_Advanced"] = "Advanced"
	L["Term_AdvancedTT"] = "Matches using advanced WoW Lua regular expressions / string patterns."

	L["Term_Blocked"] = "Messages blocked: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Enter at least one term."
	L["Term_Help"] = "Messages containing these terms are hidden. Separate terms with , (for example: gold, wts). Not case sensitive."
	L["Term_MatchType"] = "Match Type"
	L["Term_EditTitle"] = "Edit Term"
	L["Term_AddTitle"] = "Add Term"
	L["Term_Empty"] = "No filtered terms."
	L["Term_Exists"] = "Term already exists: %s"
	L["Term_Added"] = "Term added: %s"
	L["Term_Removed"] = "Term removed: %s"
	L["Terms"] = "Terms"
	L["TermsList"] = "Terms List"

	L["Verified"] = "Verified"
	L["Addon"] = "Addon"
	L["Reported"] = "Reported"
	L["GuildMute"] = "Guild Mute"
	L["CensusLeader"] = "Census Leader"
	L["CensusOfficer"] = "Census Officer"
	L["CensusTop"] = "Census Top"
	L["ChunkCensusReport"] = "Chunk (Census Report)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Inspect"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Guild Invite"

	L["LeftChannel"] = "left channel %s."

	-- for error stuff
	L["Term_Err_Length"]			= "Pattern is too long (500 max characters)."
	L["Term_Err_EndsWithPercent"]	= "Pattern can't end with a single '%'. Use '%%' for a literal percent sign."
	L["Term_Err_Balance"]			= "'%b' needs two characters after it, e.g. %b()."
	L["Term_Err_Frontier"]			= "'%f' must be followed by a set, e.g. %f[%w]."
	L["Term_Err_BackRef"]			= "Invalid back-reference: it must point to an earlier, closed capture."
	L["Term_Err_UnclosedSet"]		= "A '[' is missing its closing ']'."
	L["Term_Err_TooManyCaptures"]	= "Too many captures (32 max)."
	L["Term_Err_UnmatchedParen"]	= "There is a ')' without a matching '('."
	L["Term_Err_UnclosedParen"]		= "A '(' is missing its closing ')'."

return end

if LOCALE == "esES" or LOCALE == "esMX" then
	-- Spanish translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- Silenciar
	L["TOC_Notes"] = "Añade funciones de silencio al juego, similares a un sistema de ignorados ampliado."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/silenciarlista"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "Ahora se silenciará a %s."
	L["Ignore_Removed"] = "Ya no se silenciará a %s."
	L["Ignore_Added_Guild"] = "Ahora se silenciará a <%s>."
	L["Ignore_Removed_Guild"] = "Ya no se silenciará a <%s>."
	L["MutePlayer"] = "Silenciar jugador"
	L["UnmutePlayer"] = "Dejar de silenciar al jugador"
	L["MuteGuild"] = "Silenciar hermandad"
	L["UnmuteGuild"] = "Dejar de silenciar la hermandad"
	L["Watcher"] = "Observador"
	L["NewEntry"] = "NUEVO (%s): %s [%s]%s"
	L["NewGuild"] = "NUEVA hermandad: "
	L["MuteList"] = "Lista de silenciados"
	L["MutedPlayers_Header"] = "Jugadores silenciados (%d)"
	L["MutedGuilds_Header"] = "Hermandades silenciadas (%d)"
	L["Watchlist_Header"] = "Lista de observación (%d)"
	L["ExceptedGuilds_Header"] = "Hermandades excluidas (%d)"
	L["MutedGuild"] = "Hermandad silenciada"
	L["MutedViaGuild"] = "Silenciado mediante hermandad: <%s>"
	L["UnmutedTheGuild"] = "(Dejar de silenciar eliminará el silencio de la hermandad)"
	L["ExceptedViaGuild"] = "<%s> es una hermandad excluida"
	L["WatcherEntry"] = "Entrada del observador (%s)"
	L["GuildEntry"] = "Hermandad: <%s>"
	L["SeenCount"] = "Visto %s veces"
	L["LastSeen"] = "Visto por última vez: %s"
	L["MutedManually"] = "Silenciado manualmente"
	L["EnterEntryText"] = "Introduce el nombre del jugador o de la hermandad que quieres silenciar.\no\nHaz clic con Mayús en un nombre de la ventana de chat"
	L["NoMutedPlayers"] = "No hay jugadores silenciados."
	L["HoldShiftToConfirm"] = "Mantén pulsada la tecla Mayús para confirmar"
	L["ListeningOnChannel"] = "escuchando en el canal #%s (%s)"
	L["CouldntJoin"] = "no se pudo unir a %s (contraseña establecida, expulsado o nombre de canal reservado)"
	L["Verified"] = "Verificado"
	L["Addon"] = "Addon"
	L["Reported"] = "Reportado"
	L["Suspected"] = "Sospechoso"
	L["Exception"] = "Excepción (no silenciado)"
	L["WatcherGuild"] = "Hermandad observada"
	L["ExceptedGuild"] = "Hermandad excluida"
	L["SeenPlayersNumber"] = "Se han visto %d jugadores"
	L["PlayerIsMuted"] = "El jugador está silenciado"
	L["Guild_Exception_Added"] = "Excepción de hermandad añadida: %s"
	L["Guild_Exception_Removed"] = "Excepción de hermandad eliminada: %s"

	L["Setting_MuterHeader"] = "Silenciador"
	L["Setting_AddContextMenu"] = "Añadir menú contextual de silencio"
	L["Setting_AddContextMenuTT"] = "Añade Silenciar / Dejar de silenciar al menú del botón derecho de los jugadores."
	L["Setting_SpeechBubbles"] = "Afectar burbujas de chat"
	L["Setting_SpeechBubblesTT"] = "Activa o desactiva la ofuscación del texto de las burbujas de chat de los personajes silenciados."
	L["Setting_Chat_Notify"] = "Notificaciones de chat"
	L["Setting_Chat_NotifyTT"] = "Muestra un mensaje de chat cuando Observador encuentra una nueva entrada."
	L["Setting_PauseWatcher"] = "Pausar observador"
	L["Setting_PauseWatcherTT"] = "Pausa la recopilación de nuevas entradas. Las entradas ya recopiladas permanecen silenciadas."
	L["Setting_UseNetwork"] = "Usar red de canales"
	L["Setting_UseNetworkTT"] = "Utiliza el canal OlympusNet para recopilar una lista de silenciados para Observador.\nLos silenciados seguirán recopilándose mediante el ratón sobre la unidad, información de /who, placas de nombre y otras fuentes de unidades."

	L["Term_Contains"] = "Contiene"
	L["Term_ContainsTT"] = "Coincide en cualquier parte de un mensaje, incluso dentro de otras palabras. \"gold\" también coincide con \"golden\"."
	L["Term_Word"] = "Palabra"
	L["Term_WordTT"] = "Coincide solo cuando el término aparece como una palabra independiente. \"gold\" coincide con \"selling gold\", pero no con \"golden\"."
	L["Term_ContainsAll"] = "Contiene todo"
	L["Term_ContainsAllTT"] = "Coincide solo si el mensaje contiene todos los términos especificados (separados por comas)."
	L["Term_Advanced"] = "Avanzado"
	L["Term_AdvancedTT"] = "Busca coincidencias mediante expresiones regulares / patrones de cadenas avanzados de Lua de WoW."

	L["Term_Blocked"] = "Mensajes bloqueados: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Introduce al menos un término."
	L["Term_Help"] = "Los mensajes que contengan estos términos se ocultan. Separa los términos con , (por ejemplo: gold, wts). No distingue entre mayúsculas y minúsculas."
	L["Term_MatchType"] = "Tipo de coincidencia"
	L["Term_EditTitle"] = "Editar término"
	L["Term_AddTitle"] = "Añadir término"
	L["Term_Empty"] = "No hay términos filtrados."
	L["Term_Exists"] = "El término ya existe: %s"
	L["Term_Added"] = "Término añadido: %s"
	L["Term_Removed"] = "Término eliminado: %s"
	L["Terms"] = "Términos"
	L["TermsList"] = "Lista de términos"

	L["Verified"] = "Verificado"
	L["Addon"] = "Addon"
	L["Reported"] = "Reportado"
	L["GuildMute"] = "Silencio de hermandad"
	L["CensusLeader"] = "Líder del censo"
	L["CensusOfficer"] = "Oficial del censo"
	L["CensusTop"] = "Parte superior del censo"
	L["ChunkCensusReport"] = "Fragmento (informe del censo)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Inspeccionar"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Invitación de hermandad"

	L["LeftChannel"] = "ha abandonado el canal %s."

return end

if LOCALE == "deDE" then
	-- German translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- Stumm
	L["TOC_Notes"] = "Fügt dem Spiel Stummschaltungsfunktionen hinzu, ähnlich einem erweiterten Ignoriersystem."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/stummelliste"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s wird nun stummgeschaltet."
	L["Ignore_Removed"] = "%s wird nicht mehr stummgeschaltet."
	L["Ignore_Added_Guild"] = "<%s> wird nun stummgeschaltet."
	L["Ignore_Removed_Guild"] = "<%s> wird nicht mehr stummgeschaltet."
	L["MutePlayer"] = "Spieler stummschalten"
	L["UnmutePlayer"] = "Spieler nicht mehr stummschalten"
	L["MuteGuild"] = "Gilde stummschalten"
	L["UnmuteGuild"] = "Gilde nicht mehr stummschalten"
	L["Watcher"] = "Beobachter"
	L["NewEntry"] = "NEU (%s): %s [%s]%s"
	L["NewGuild"] = "NEUE Gilde: "
	L["MuteList"] = "Stummschaltungsliste"
	L["MutedPlayers_Header"] = "Stummgeschaltete Spieler (%d)"
	L["MutedGuilds_Header"] = "Stummgeschaltete Gilden (%d)"
	L["Watchlist_Header"] = "Beobachtungsliste (%d)"
	L["ExceptedGuilds_Header"] = "Ausgenommene Gilden (%d)"
	L["MutedGuild"] = "Stummgeschaltete Gilde"
	L["MutedViaGuild"] = "Über Gilde stummgeschaltet: <%s>"
	L["UnmutedTheGuild"] = "(Das Aufheben der Stummschaltung hebt die Stummschaltung der Gilde auf)"
	L["ExceptedViaGuild"] = "<%s> ist eine ausgenommene Gilde"
	L["WatcherEntry"] = "Beobachtungseintrag (%s)"
	L["GuildEntry"] = "Gilde: <%s>"
	L["SeenCount"] = "%s-mal gesehen"
	L["LastSeen"] = "Zuletzt gesehen: %s"
	L["MutedManually"] = "Manuell stummgeschaltet"
	L["EnterEntryText"] = "Gib den Namen des Spielers oder der Gilde ein, die stummgeschaltet werden soll.\noder\nHalte Umschalt gedrückt und klicke auf einen Namen im Chatfenster"
	L["NoMutedPlayers"] = "Keine stummgeschalteten Spieler."
	L["HoldShiftToConfirm"] = "Umschalt zum Bestätigen gedrückt halten"
	L["ListeningOnChannel"] = "lauscht auf Kanal #%s (%s)"
	L["CouldntJoin"] = "Beitritt zu %s nicht möglich (Passwort festgelegt, gebannt oder versiegelter Kanalname)"
	L["Verified"] = "Verifiziert"
	L["Addon"] = "Addon"
	L["Reported"] = "Gemeldet"
	L["Suspected"] = "Verdächtig"
	L["Exception"] = "Ausnahme (nicht stummgeschaltet)"
	L["WatcherGuild"] = "Beobachtete Gilde"
	L["ExceptedGuild"] = "Ausgenommene Gilde"
	L["SeenPlayersNumber"] = "%d Spieler gesehen"
	L["PlayerIsMuted"] = "Spieler ist stummgeschaltet"
	L["Guild_Exception_Added"] = "Gildenausnahme hinzugefügt: %s"
	L["Guild_Exception_Removed"] = "Gildenausnahme entfernt: %s"

	L["Setting_MuterHeader"] = "Stummschalter"
	L["Setting_AddContextMenu"] = "Stummschaltungs-Kontextmenü hinzufügen"
	L["Setting_AddContextMenuTT"] = "Fügt Stummschalten / Stummschaltung aufheben zum Rechtsklickmenü von Spielern hinzu."
	L["Setting_SpeechBubbles"] = "Chatblasen beeinflussen"
	L["Setting_SpeechBubblesTT"] = "Legt fest, ob der Text von Chatblasen stummgeschalteter Charaktere verschleiert wird."
	L["Setting_Chat_Notify"] = "Chatbenachrichtigungen"
	L["Setting_Chat_NotifyTT"] = "Gibt eine Chatnachricht aus, wenn der Beobachter einen neuen Eintrag erfasst."
	L["Setting_PauseWatcher"] = "Beobachter pausieren"
	L["Setting_PauseWatcherTT"] = "Pausiert das Erfassen neuer Einträge. Bereits erfasste Einträge bleiben stummgeschaltet."
	L["Setting_UseNetwork"] = "Kanalnetzwerk verwenden"
	L["Setting_UseNetworkTT"] = "Verwendet den OlympusNet-Kanal, um eine Stummschaltungsliste für den Beobachter zu erfassen.\nStummschaltungen werden weiterhin über Mouseover, /who-Informationen, Namensplaketten und andere Einheitenquellen erfasst."

	L["Term_Contains"] = "Enthält"
	L["Term_ContainsTT"] = "Stimmt an beliebiger Stelle in einer Nachricht überein, auch innerhalb anderer Wörter. \"gold\" stimmt auch mit \"golden\" überein."
	L["Term_Word"] = "Wort"
	L["Term_WordTT"] = "Stimmt nur überein, wenn der Begriff für sich allein steht. \"gold\" stimmt mit \"selling gold\", aber nicht mit \"golden\" überein."
	L["Term_ContainsAll"] = "Enthält alle"
	L["Term_ContainsAllTT"] = "Stimmt nur überein, wenn die Nachricht alle angegebenen Begriffe enthält (durch Kommas getrennt)."
	L["Term_Advanced"] = "Erweitert"
	L["Term_AdvancedTT"] = "Verwendet erweiterte reguläre Ausdrücke / Zeichenkettenmuster der WoW-Lua-Sprache."

	L["Term_Blocked"] = "Blockierte Nachrichten: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Gib mindestens einen Begriff ein."
	L["Term_Help"] = "Nachrichten, die diese Begriffe enthalten, werden ausgeblendet. Trenne Begriffe mit , (zum Beispiel: gold, wts). Groß-/Kleinschreibung wird nicht berücksichtigt."
	L["Term_MatchType"] = "Übereinstimmungstyp"
	L["Term_EditTitle"] = "Begriff bearbeiten"
	L["Term_AddTitle"] = "Begriff hinzufügen"
	L["Term_Empty"] = "Keine gefilterten Begriffe."
	L["Term_Exists"] = "Begriff existiert bereits: %s"
	L["Term_Added"] = "Begriff hinzugefügt: %s"
	L["Term_Removed"] = "Begriff entfernt: %s"
	L["Terms"] = "Begriffe"
	L["TermsList"] = "Begriffsliste"

	L["Verified"] = "Verifiziert"
	L["Addon"] = "Addon"
	L["Reported"] = "Gemeldet"
	L["GuildMute"] = "Gildenstummschaltung"
	L["CensusLeader"] = "Zensusanführer"
	L["CensusOfficer"] = "Zensusoffizier"
	L["CensusTop"] = "Zensus-Spitze"
	L["ChunkCensusReport"] = "Abschnitt (Zensusbericht)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Untersuchen"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Gildeneinladung"

	L["LeftChannel"] = "hat den Kanal %s verlassen."

return end

if LOCALE == "frFR" then
	-- French translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- Muet
	L["TOC_Notes"] = "Ajoute des fonctions de silence au jeu, similaires à un système d’ignorés étendu."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/muetliste"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s est désormais réduit au silence."
	L["Ignore_Removed"] = "%s n'est plus réduit au silence."
	L["Ignore_Added_Guild"] = "<%s> est désormais réduit au silence."
	L["Ignore_Removed_Guild"] = "<%s> n'est plus réduit au silence."
	L["MutePlayer"] = "Réduire le joueur au silence"
	L["UnmutePlayer"] = "Ne plus réduire le joueur au silence"
	L["MuteGuild"] = "Réduire la guilde au silence"
	L["UnmuteGuild"] = "Ne plus réduire la guilde au silence"
	L["Watcher"] = "Observateur"
	L["NewEntry"] = "NOUVEAU (%s) : %s [%s]%s"
	L["NewGuild"] = "NOUVELLE guilde : "
	L["MuteList"] = "Liste des silences"
	L["MutedPlayers_Header"] = "Joueurs réduits au silence (%d)"
	L["MutedGuilds_Header"] = "Guildes réduites au silence (%d)"
	L["Watchlist_Header"] = "Liste de surveillance (%d)"
	L["ExceptedGuilds_Header"] = "Guildes exclues (%d)"
	L["MutedGuild"] = "Guilde réduite au silence"
	L["MutedViaGuild"] = "Réduit au silence via la guilde : <%s>"
	L["UnmutedTheGuild"] = "(Ne plus réduire au silence retirera également le silence de la guilde)"
	L["ExceptedViaGuild"] = "<%s> est une guilde exclue"
	L["WatcherEntry"] = "Entrée de surveillance (%s)"
	L["GuildEntry"] = "Guilde : <%s>"
	L["SeenCount"] = "Vu %s fois"
	L["LastSeen"] = "Vu pour la dernière fois : %s"
	L["MutedManually"] = "Réduit au silence manuellement"
	L["EnterEntryText"] = "Saisissez le nom du joueur ou de la guilde à réduire au silence.\nou\nMaj-clic sur un nom dans la fenêtre de discussion"
	L["NoMutedPlayers"] = "Aucun joueur réduit au silence."
	L["HoldShiftToConfirm"] = "Maintenez Maj pour confirmer"
	L["ListeningOnChannel"] = "écoute sur le canal n°%s (%s)"
	L["CouldntJoin"] = "impossible de rejoindre %s (mot de passe défini, banni ou nom de canal scellé)"
	L["Verified"] = "Vérifié"
	L["Addon"] = "Addon"
	L["Reported"] = "Signalé"
	L["Suspected"] = "Suspect"
	L["Exception"] = "Exception (non réduit au silence)"
	L["WatcherGuild"] = "Guilde surveillée"
	L["ExceptedGuild"] = "Guilde exclue"
	L["SeenPlayersNumber"] = "%d joueurs vus"
	L["PlayerIsMuted"] = "Le joueur est réduit au silence"
	L["Guild_Exception_Added"] = "Exception de guilde ajoutée : %s"
	L["Guild_Exception_Removed"] = "Exception de guilde supprimée : %s"

	L["Setting_MuterHeader"] = "Réducteur au silence"
	L["Setting_AddContextMenu"] = "Ajouter le menu contextuel de silence"
	L["Setting_AddContextMenuTT"] = "Ajoute Réduire au silence / Ne plus réduire au silence au menu clic droit des joueurs."
	L["Setting_SpeechBubbles"] = "Affecter les bulles de discussion"
	L["Setting_SpeechBubblesTT"] = "Active ou désactive la dissimulation du texte des bulles de discussion des personnages réduits au silence."
	L["Setting_Chat_Notify"] = "Notifications de discussion"
	L["Setting_Chat_NotifyTT"] = "Affiche un message dans la discussion lorsque le surveillant recueille une nouvelle entrée."
	L["Setting_PauseWatcher"] = "Mettre le surveillant en pause"
	L["Setting_PauseWatcherTT"] = "Met en pause la collecte de nouvelles entrées. Les entrées déjà recueillies restent réduites au silence."
	L["Setting_UseNetwork"] = "Utiliser le réseau de canaux"
	L["Setting_UseNetworkTT"] = "Utilise le canal OlympusNet pour recueillir une liste de personnes réduites au silence pour le surveillant.\nLes personnes réduites au silence continueront d'être recueillies via le survol de la souris, les informations /who, les plaques de nom et d'autres sources d'unités."

	L["Term_Contains"] = "Contient"
	L["Term_ContainsTT"] = "Correspond n'importe où dans un message, même à l'intérieur d'autres mots. \"gold\" correspond également à \"golden\"."
	L["Term_Word"] = "Mot"
	L["Term_WordTT"] = "Correspond uniquement lorsque le terme constitue un mot à part entière. \"gold\" correspond à \"selling gold\", mais pas à \"golden\"."
	L["Term_ContainsAll"] = "Contient tout"
	L["Term_ContainsAllTT"] = "Correspond uniquement si le message contient tous les termes spécifiés (séparés par des virgules)."
	L["Term_Advanced"] = "Avancé"
	L["Term_AdvancedTT"] = "Effectue les correspondances à l'aide des expressions régulières / modèles de chaînes Lua avancés de WoW."
	L["Term_Blocked"] = "Messages bloqués : %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Saisissez au moins un terme."
	L["Term_Help"] = "Les messages contenant ces termes sont masqués. Séparez les termes avec , (par exemple : gold, wts). La casse n'est pas prise en compte."
	L["Term_MatchType"] = "Type de correspondance"
	L["Term_EditTitle"] = "Modifier le terme"
	L["Term_AddTitle"] = "Ajouter un terme"
	L["Term_Empty"] = "Aucun terme filtré."
	L["Term_Exists"] = "Le terme existe déjà : %s"
	L["Term_Added"] = "Terme ajouté : %s"
	L["Term_Removed"] = "Terme supprimé : %s"
	L["Terms"] = "Termes"
	L["TermsList"] = "Liste des termes"

	L["Verified"] = "Vérifié"
	L["Addon"] = "Addon"
	L["Reported"] = "Signalé"
	L["GuildMute"] = "Silence de guilde"
	L["CensusLeader"] = "Chef du recensement"
	L["CensusOfficer"] = "Officier du recensement"
	L["CensusTop"] = "Sommet du recensement"
	L["ChunkCensusReport"] = "Segment (rapport de recensement)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Inspecter"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Invitation de guilde"

	L["LeftChannel"] = "a quitté le canal %s."

return end

if LOCALE == "itIT" then
	-- French translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- Silenzia
	L["TOC_Notes"] = "Aggiunge funzioni di silenziamento al gioco, simili a un sistema di ignorati ampliato."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/silenzialista"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s è ora silenziato."
	L["Ignore_Removed"] = "%s non è più silenziato."
	L["Ignore_Added_Guild"] = "<%s> è ora silenziata."
	L["Ignore_Removed_Guild"] = "<%s> non è più silenziata."
	L["MutePlayer"] = "Silenzia giocatore"
	L["UnmutePlayer"] = "Rimuovi silenziamento giocatore"
	L["MuteGuild"] = "Silenzia gilda"
	L["UnmuteGuild"] = "Rimuovi silenziamento gilda"
	L["Watcher"] = "Osservatore"
	L["NewEntry"] = "NUOVO (%s): %s [%s]%s"
	L["NewGuild"] = "NUOVA gilda: "
	L["MuteList"] = "Elenco dei silenziati"
	L["MutedPlayers_Header"] = "Giocatori silenziati (%d)"
	L["MutedGuilds_Header"] = "Gilde silenziate (%d)"
	L["Watchlist_Header"] = "Lista di osservazione (%d)"
	L["ExceptedGuilds_Header"] = "Gilde escluse (%d)"
	L["MutedGuild"] = "Gilda silenziata"
	L["MutedViaGuild"] = "Silenziato tramite gilda: <%s>"
	L["UnmutedTheGuild"] = "(Rimuovendo il silenziamento verrà rimosso anche quello della gilda)"
	L["ExceptedViaGuild"] = "<%s> è una gilda esclusa"
	L["WatcherEntry"] = "Voce osservatore (%s)"
	L["GuildEntry"] = "Gilda: <%s>"
	L["SeenCount"] = "Visto %s volte"
	L["LastSeen"] = "Visto l'ultima volta: %s"
	L["MutedManually"] = "Silenziato manualmente"
	L["EnterEntryText"] = "Inserisci il nome del giocatore o della gilda da silenziare.\no\nFai clic tenendo premuto Maiusc su un nome nella finestra della chat"
	L["NoMutedPlayers"] = "Nessun giocatore silenziato."
	L["HoldShiftToConfirm"] = "Tieni premuto Maiusc per confermare"
	L["ListeningOnChannel"] = "in ascolto sul canale #%s (%s)"
	L["CouldntJoin"] = "impossibile entrare in %s (password impostata, bannato o nome del canale sigillato)"
	L["Verified"] = "Verificato"
	L["Addon"] = "Addon"
	L["Reported"] = "Segnalato"
	L["Suspected"] = "Sospetto"
	L["Exception"] = "Eccezione (non silenziato)"
	L["WatcherGuild"] = "Gilda osservata"
	L["ExceptedGuild"] = "Gilda esclusa"
	L["SeenPlayersNumber"] = "Visti %d giocatori"
	L["PlayerIsMuted"] = "Il giocatore è silenziato"
	L["Guild_Exception_Added"] = "Eccezione gilda aggiunta: %s"
	L["Guild_Exception_Removed"] = "Eccezione gilda rimossa: %s"

	L["Setting_MuterHeader"] = "Silenziatore"
	L["Setting_AddContextMenu"] = "Aggiungi menu contestuale del silenziamento"
	L["Setting_AddContextMenuTT"] = "Aggiunge Silenzia / Rimuovi silenziamento al menu del clic destro dei giocatori."
	L["Setting_SpeechBubbles"] = "Influenza le bolle della chat"
	L["Setting_SpeechBubblesTT"] = "Attiva o disattiva l'offuscamento del testo nelle bolle della chat dei personaggi silenziati."
	L["Setting_Chat_Notify"] = "Notifiche della chat"
	L["Setting_Chat_NotifyTT"] = "Mostra un messaggio in chat quando Osservatore raccoglie una nuova voce."
	L["Setting_PauseWatcher"] = "Metti in pausa Osservatore"
	L["Setting_PauseWatcherTT"] = "Mette in pausa la raccolta di nuove voci. Le voci già raccolte rimangono silenziate."
	L["Setting_UseNetwork"] = "Usa rete dei canali"
	L["Setting_UseNetworkTT"] = "Utilizza il canale OlympusNet per raccogliere un elenco dei silenziati per Osservatore.\nI silenziati continueranno a essere raccolti tramite passaggio del mouse, informazioni /who, piastre dei nomi e altre fonti di unità."

	L["Term_Contains"] = "Contiene"
	L["Term_ContainsTT"] = "Corrisponde in qualsiasi punto di un messaggio, anche all'interno di altre parole. \"gold\" corrisponde anche a \"golden\"."
	L["Term_Word"] = "Parola"
	L["Term_WordTT"] = "Corrisponde solo quando il termine è una parola a sé stante. \"gold\" corrisponde a \"selling gold\", ma non a \"golden\"."
	L["Term_ContainsAll"] = "Contiene tutto"
	L["Term_ContainsAllTT"] = "Corrisponde solo se il messaggio contiene tutti i termini specificati (separati da virgole)."
	L["Term_Advanced"] = "Avanzato"
	L["Term_AdvancedTT"] = "Corrisponde utilizzando espressioni regolari / modelli di stringhe Lua avanzati di WoW."
	L["Term_Blocked"] = "Messaggi bloccati: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Inserisci almeno un termine."
	L["Term_Help"] = "I messaggi contenenti questi termini vengono nascosti. Separa i termini con , (ad esempio: gold, wts). Non distingue tra maiuscole e minuscole."
	L["Term_MatchType"] = "Tipo di corrispondenza"
	L["Term_EditTitle"] = "Modifica termine"
	L["Term_AddTitle"] = "Aggiungi termine"
	L["Term_Empty"] = "Nessun termine filtrato."
	L["Term_Exists"] = "Il termine esiste già: %s"
	L["Term_Added"] = "Termine aggiunto: %s"
	L["Term_Removed"] = "Termine rimosso: %s"
	L["Terms"] = "Termini"
	L["TermsList"] = "Elenco termini"

	L["Verified"] = "Verificato"
	L["Addon"] = "Addon"
	L["Reported"] = "Segnalato"
	L["GuildMute"] = "Silenziamento gilda"
	L["CensusLeader"] = "Capo del censimento"
	L["CensusOfficer"] = "Ufficiale del censimento"
	L["CensusTop"] = "Vertice del censimento"
	L["ChunkCensusReport"] = "Blocco (rapporto censimento)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Ispeziona"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Invito in gilda"

	L["LeftChannel"] = "ha lasciato il canale %s."

return end

if LOCALE == "ptBR" then
	-- Brazilian Portuguese translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- Silenciar
	L["TOC_Notes"] = "Adiciona funções de silêncio ao jogo, semelhantes a um sistema de ignorados expandido."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/silenciarlista"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s agora está silenciado."
	L["Ignore_Removed"] = "%s não está mais silenciado."
	L["Ignore_Added_Guild"] = "<%s> agora está silenciada."
	L["Ignore_Removed_Guild"] = "<%s> não está mais silenciada."
	L["MutePlayer"] = "Silenciar jogador"
	L["UnmutePlayer"] = "Remover silêncio do jogador"
	L["MuteGuild"] = "Silenciar guilda"
	L["UnmuteGuild"] = "Remover silêncio da guilda"
	L["Watcher"] = "Observador"
	L["NewEntry"] = "NOVO (%s): %s [%s]%s"
	L["NewGuild"] = "NOVA guilda: "
	L["MuteList"] = "Lista de silenciados"
	L["MutedPlayers_Header"] = "Jogadores silenciados (%d)"
	L["MutedGuilds_Header"] = "Guildas silenciadas (%d)"
	L["Watchlist_Header"] = "Lista de observação (%d)"
	L["ExceptedGuilds_Header"] = "Guildas excluídas (%d)"
	L["MutedGuild"] = "Guilda silenciada"
	L["MutedViaGuild"] = "Silenciado pela guilda: <%s>"
	L["UnmutedTheGuild"] = "(Remover o silêncio também removerá o silêncio da guilda)"
	L["ExceptedViaGuild"] = "<%s> é uma guilda excluída"
	L["WatcherEntry"] = "Entrada do observador (%s)"
	L["GuildEntry"] = "Guilda: <%s>"
	L["SeenCount"] = "Visto %s vezes"
	L["LastSeen"] = "Visto pela última vez: %s"
	L["MutedManually"] = "Silenciado manualmente"
	L["EnterEntryText"] = "Digite o nome do jogador ou da guilda a ser silenciado.\nou\nClique com Shift em um nome na janela de bate-papo"
	L["NoMutedPlayers"] = "Nenhum jogador silenciado."
	L["HoldShiftToConfirm"] = "Segure Shift para confirmar"
	L["ListeningOnChannel"] = "ouvindo no canal #%s (%s)"
	L["CouldntJoin"] = "não foi possível entrar em %s (senha definida, banido ou nome de canal selado)"
	L["Verified"] = "Verificado"
	L["Addon"] = "Addon"
	L["Reported"] = "Denunciado"
	L["Suspected"] = "Suspeito"
	L["Exception"] = "Exceção (não silenciado)"
	L["WatcherGuild"] = "Guilda observada"
	L["ExceptedGuild"] = "Guilda excluída"
	L["SeenPlayersNumber"] = "%d jogadores vistos"
	L["PlayerIsMuted"] = "O jogador está silenciado"
	L["Guild_Exception_Added"] = "Exceção de guilda adicionada: %s"
	L["Guild_Exception_Removed"] = "Exceção de guilda removida: %s"

	L["Setting_MuterHeader"] = "Silenciador"
	L["Setting_AddContextMenu"] = "Adicionar menu de contexto de silêncio"
	L["Setting_AddContextMenuTT"] = "Adiciona Silenciar / Remover silêncio ao menu de contexto dos jogadores."
	L["Setting_SpeechBubbles"] = "Afetar balões de fala"
	L["Setting_SpeechBubblesTT"] = "Alterna se o texto dos balões de fala de personagens silenciados será ofuscado."
	L["Setting_Chat_Notify"] = "Notificações do chat"
	L["Setting_Chat_NotifyTT"] = "Exibe uma mensagem no chat quando o Observador coleta uma nova entrada."
	L["Setting_PauseWatcher"] = "Pausar Observador"
	L["Setting_PauseWatcherTT"] = "Pausa a coleta de novas entradas. As entradas já coletadas continuam silenciadas."
	L["Setting_UseNetwork"] = "Usar rede de canais"
	L["Setting_UseNetworkTT"] = "Utiliza o canal OlympusNet para coletar uma lista de silenciados para o Observador.\nOs silenciados continuarão sendo coletados por mouseover, informações de /who, placas de identificação e outras fontes de unidades."

	L["Term_Contains"] = "Contém"
	L["Term_ContainsTT"] = "Corresponde em qualquer parte de uma mensagem, mesmo dentro de outras palavras. \"gold\" também corresponde a \"golden\"."
	L["Term_Word"] = "Palavra"
	L["Term_WordTT"] = "Corresponde somente quando o termo aparece sozinho. \"gold\" corresponde a \"selling gold\", mas não a \"golden\"."
	L["Term_ContainsAll"] = "Contém tudo"
	L["Term_ContainsAllTT"] = "Corresponde somente se a mensagem contiver todos os termos especificados (separados por vírgulas)."
	L["Term_Advanced"] = "Avançado"
	L["Term_AdvancedTT"] = "Corresponde usando expressões regulares / padrões de strings avançados de Lua do WoW."
	L["Term_Blocked"] = "Mensagens bloqueadas: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Digite pelo menos um termo."
	L["Term_Help"] = "Mensagens que contêm esses termos são ocultadas. Separe os termos com , (por exemplo: gold, wts). Não diferencia maiúsculas de minúsculas."
	L["Term_MatchType"] = "Tipo de correspondência"
	L["Term_EditTitle"] = "Editar termo"
	L["Term_AddTitle"] = "Adicionar termo"
	L["Term_Empty"] = "Nenhum termo filtrado."
	L["Term_Exists"] = "O termo já existe: %s"
	L["Term_Added"] = "Termo adicionado: %s"
	L["Term_Removed"] = "Termo removido: %s"
	L["Terms"] = "Termos"
	L["TermsList"] = "Lista de termos"

	L["Verified"] = "Verificado"
	L["Addon"] = "Addon"
	L["Reported"] = "Denunciado"
	L["GuildMute"] = "Silêncio da guilda"
	L["CensusLeader"] = "Líder do censo"
	L["CensusOfficer"] = "Oficial do censo"
	L["CensusTop"] = "Topo do censo"
	L["ChunkCensusReport"] = "Bloco (relatório do censo)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Inspecionar"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Convite para guilda"

	L["LeftChannel"] = "saiu do canal %s."

	-- Note that the EU Portuguese WoW client also
	-- uses the Brazilian Portuguese locale code.
return end

if LOCALE == "ruRU" then
	-- Russian translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- Отключить звук
	L["TOC_Notes"] = "Добавляет в игру функции заглушения, аналогичные расширенной системе игнорирования."
	L["SLASH_CHAT_MUTE1"] = SLASH_CHAT_MUTE1
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/отключитьзвуксписок"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s теперь заглушён."
	L["Ignore_Removed"] = "%s больше не заглушён."
	L["Ignore_Added_Guild"] = "<%s> теперь заглушена."
	L["Ignore_Removed_Guild"] = "<%s> больше не заглушена."
	L["MutePlayer"] = "Заглушить игрока"
	L["UnmutePlayer"] = "Снять заглушение с игрока"
	L["MuteGuild"] = "Заглушить гильдию"
	L["UnmuteGuild"] = "Снять заглушение с гильдии"
	L["Watcher"] = "Наблюдатель"
	L["NewEntry"] = "НОВЫЙ (%s): %s [%s]%s"
	L["NewGuild"] = "НОВАЯ гильдия: "
	L["MuteList"] = "Список заглушенных"
	L["MutedPlayers_Header"] = "Заглушённые игроки (%d)"
	L["MutedGuilds_Header"] = "Заглушённые гильдии (%d)"
	L["Watchlist_Header"] = "Список наблюдения (%d)"
	L["ExceptedGuilds_Header"] = "Исключённые гильдии (%d)"
	L["MutedGuild"] = "Заглушённая гильдия"
	L["MutedViaGuild"] = "Заглушён через гильдию: <%s>"
	L["UnmutedTheGuild"] = "(Снятие заглушения также снимет заглушение с гильдии)"
	L["ExceptedViaGuild"] = "<%s> — исключённая гильдия"
	L["WatcherEntry"] = "Запись наблюдателя (%s)"
	L["GuildEntry"] = "Гильдия: <%s>"
	L["SeenCount"] = "Встречается %s раз"
	L["LastSeen"] = "Последний раз замечен: %s"
	L["MutedManually"] = "Заглушён вручную"
	L["EnterEntryText"] = "Введите имя игрока или гильдии, которую нужно заглушить.\nили\nЩёлкните по имени в окне чата, удерживая Shift"
	L["NoMutedPlayers"] = "Нет заглушённых игроков."
	L["HoldShiftToConfirm"] = "Удерживайте Shift для подтверждения"
	L["ListeningOnChannel"] = "прослушивает канал #%s (%s)"
	L["CouldntJoin"] = "не удалось присоединиться к %s (установлен пароль, заблокирован или имя канала запечатано)"
	L["Verified"] = "Проверено"
	L["Addon"] = "Аддон"
	L["Reported"] = "Пожалован"
	L["Suspected"] = "Подозрительный"
	L["Exception"] = "Исключение (не заглушён)"
	L["WatcherGuild"] = "Наблюдаемая гильдия"
	L["ExceptedGuild"] = "Исключённая гильдия"
	L["SeenPlayersNumber"] = "Замечено игроков: %d"
	L["PlayerIsMuted"] = "Игрок заглушён"
	L["Guild_Exception_Added"] = "Добавлено исключение для гильдии: %s"
	L["Guild_Exception_Removed"] = "Удалено исключение для гильдии: %s"

	L["Setting_MuterHeader"] = "Заглушение"
	L["Setting_AddContextMenu"] = "Добавить контекстное меню заглушения"
	L["Setting_AddContextMenuTT"] = "Добавляет пункты «Заглушить / Снять заглушение» в контекстное меню игроков."
	L["Setting_SpeechBubbles"] = "Влиять на реплики"
	L["Setting_SpeechBubblesTT"] = "Включает или отключает скрытие текста в репликах заглушённых персонажей."
	L["Setting_Chat_Notify"] = "Уведомления в чате"
	L["Setting_Chat_NotifyTT"] = "Выводит сообщение в чат, когда Наблюдатель получает новую запись."
	L["Setting_PauseWatcher"] = "Приостановить наблюдателя"
	L["Setting_PauseWatcherTT"] = "Приостанавливает сбор новых записей. Уже собранные записи остаются заглушёнными."
	L["Setting_UseNetwork"] = "Использовать сеть каналов"
	L["Setting_UseNetworkTT"] = "Использует канал OlympusNet для сбора списка заглушённых игроков для Наблюдателя.\nЗаглушённые игроки по-прежнему будут собираться через наведение мыши, информацию /who, индикаторы имени и другие источники данных об объектах."

	L["Term_Contains"] = "Содержит"
	L["Term_ContainsTT"] = "Совпадает в любом месте сообщения, даже внутри других слов. \"gold\" также совпадает с \"golden\"."
	L["Term_Word"] = "Слово"
	L["Term_WordTT"] = "Совпадает только тогда, когда термин является отдельным словом. \"gold\" совпадает с \"selling gold\", но не с \"golden\"."
	L["Term_ContainsAll"] = "Содержит всё"
	L["Term_ContainsAllTT"] = "Совпадает только в том случае, если сообщение содержит все указанные термины (разделённые запятыми)."
	L["Term_Advanced"] = "Расширенный"
	L["Term_AdvancedTT"] = "Использует расширенные регулярные выражения / шаблоны строк Lua в WoW."
	L["Term_Blocked"] = "Заблокировано сообщений: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "Введите хотя бы один термин."
	L["Term_Help"] = "Сообщения, содержащие эти термины, скрываются. Разделяйте термины запятыми (например: gold, wts). Регистр не учитывается."
	L["Term_MatchType"] = "Тип совпадения"
	L["Term_EditTitle"] = "Изменить термин"
	L["Term_AddTitle"] = "Добавить термин"
	L["Term_Empty"] = "Нет отфильтрованных терминов."
	L["Term_Exists"] = "Термин уже существует: %s"
	L["Term_Added"] = "Термин добавлен: %s"
	L["Term_Removed"] = "Термин удалён: %s"
	L["Terms"] = "Термины"
	L["TermsList"] = "Список терминов"

	L["Verified"] = "Проверено"
	L["Addon"] = "Аддон"
	L["Reported"] = "Пожаловано"
	L["GuildMute"] = "Заглушение гильдии"
	L["CensusLeader"] = "Лидер переписи"
	L["CensusOfficer"] = "Офицер переписи"
	L["CensusTop"] = "Топ переписи"
	L["ChunkCensusReport"] = "Фрагмент (отчёт переписи)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "Осмотреть"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "Приглашение в гильдию"

	L["LeftChannel"] = "покинул канал %s."

return end

if LOCALE == "koKR" then
	-- Korean translations go here
	L["MUTE"] = "무음"
	L["TOC_Title"] = "무음"
	L["TOC_Notes"] = "확장된 무시 시스템과 유사한 음소거 기능을 게임에 추가합니다."
	L["SLASH_CHAT_MUTE1"] = "/무음"
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/무음목록"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "%s 님을 음소거합니다."
	L["Ignore_Removed"] = "%s 님의 음소거를 해제합니다."
	L["Ignore_Added_Guild"] = "<%s> 길드를 음소거합니다."
	L["Ignore_Removed_Guild"] = "<%s> 길드의 음소거를 해제합니다."
	L["MutePlayer"] = "플레이어 음소거"
	L["UnmutePlayer"] = "플레이어 음소거 해제"
	L["MuteGuild"] = "길드 음소거"
	L["UnmuteGuild"] = "길드 음소거 해제"
	L["Watcher"] = "감시자"
	L["NewEntry"] = "새 항목 (%s): %s [%s]%s"
	L["NewGuild"] = "새 길드: "
	L["MuteList"] = "음소거 목록"
	L["MutedPlayers_Header"] = "음소거된 플레이어 (%d)"
	L["MutedGuilds_Header"] = "음소거된 길드 (%d)"
	L["Watchlist_Header"] = "감시 목록 (%d)"
	L["ExceptedGuilds_Header"] = "제외된 길드 (%d)"
	L["MutedGuild"] = "음소거된 길드"
	L["MutedViaGuild"] = "길드를 통해 음소거됨: <%s>"
	L["UnmutedTheGuild"] = "(음소거를 해제하면 해당 길드의 음소거도 해제됩니다)"
	L["ExceptedViaGuild"] = "<%s>은(는) 예외 길드입니다"
	L["WatcherEntry"] = "감시 항목 (%s)"
	L["GuildEntry"] = "길드: <%s>"
	L["SeenCount"] = "%s회 발견됨"
	L["LastSeen"] = "마지막 발견: %s"
	L["MutedManually"] = "수동으로 음소거됨"
	L["EnterEntryText"] = "음소거할 플레이어 또는 길드의 이름을 입력하세요.\n또는\n채팅창에서 이름을 Shift 클릭하세요"
	L["NoMutedPlayers"] = "음소거된 플레이어가 없습니다."
	L["HoldShiftToConfirm"] = "Shift 키를 눌러 확인"
	L["ListeningOnChannel"] = "채널 #%s (%s) 수신 중"
	L["CouldntJoin"] = "%s에 참가할 수 없습니다 (비밀번호 설정, 차단됨 또는 봉인된 채널 이름)"
	L["Verified"] = "확인됨"
	L["Addon"] = "애드온"
	L["Reported"] = "신고됨"
	L["Suspected"] = "의심됨"
	L["Exception"] = "예외 (음소거하지 않음)"
	L["WatcherGuild"] = "감시 길드"
	L["ExceptedGuild"] = "예외 길드"
	L["SeenPlayersNumber"] = "%d명의 플레이어 발견"
	L["PlayerIsMuted"] = "플레이어가 음소거되었습니다"
	L["Guild_Exception_Added"] = "길드 예외 추가: %s"
	L["Guild_Exception_Removed"] = "길드 예외 제거: %s"

	L["Setting_MuterHeader"] = "음소거"
	L["Setting_AddContextMenu"] = "음소거 컨텍스트 메뉴 추가"
	L["Setting_AddContextMenuTT"] = "플레이어 우클릭 메뉴에 음소거 / 음소거 해제를 추가합니다."
	L["Setting_SpeechBubbles"] = "말풍선에 적용"
	L["Setting_SpeechBubblesTT"] = "음소거된 캐릭터의 말풍선 텍스트를 난독화할지 설정합니다."
	L["Setting_Chat_Notify"] = "채팅 알림"
	L["Setting_Chat_NotifyTT"] = "감시자가 새로운 항목을 수집하면 채팅 메시지를 표시합니다."
	L["Setting_PauseWatcher"] = "감시자 일시정지"
	L["Setting_PauseWatcherTT"] = "새로운 항목 수집을 일시정지합니다. 이미 수집된 항목은 계속 음소거됩니다."
	L["Setting_UseNetwork"] = "채널 네트워크 사용"
	L["Setting_UseNetworkTT"] = "OlympusNet 채널을 사용하여 감시자의 음소거 목록을 수집합니다.\n마우스 오버, /who 정보, 이름표 및 기타 유닛 소스를 통한 음소거 수집은 계속됩니다."

	L["Term_Contains"] = "포함"
	L["Term_ContainsTT"] = "다른 단어 내부를 포함하여 메시지의 어느 위치에서든 일치합니다. \"gold\"는 \"golden\"에도 일치합니다."
	L["Term_Word"] = "단어"
	L["Term_WordTT"] = "해당 용어가 독립된 단어로 있을 때만 일치합니다. \"gold\"는 \"selling gold\"에는 일치하지만 \"golden\"에는 일치하지 않습니다."
	L["Term_ContainsAll"] = "모두 포함"
	L["Term_ContainsAllTT"] = "메시지에 지정된 모든 용어가 포함된 경우에만 일치합니다(쉼표로 구분)."
	L["Term_Advanced"] = "고급"
	L["Term_AdvancedTT"] = "WoW Lua의 고급 정규 표현식 / 문자열 패턴을 사용하여 일치시킵니다."
	L["Term_Blocked"] = "차단된 메시지: %d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "하나 이상의 용어를 입력하세요."
	L["Term_Help"] = "이 용어가 포함된 메시지는 숨겨집니다. 용어는 ,로 구분하세요 (예: gold, wts). 대소문자를 구분하지 않습니다."
	L["Term_MatchType"] = "일치 유형"
	L["Term_EditTitle"] = "용어 편집"
	L["Term_AddTitle"] = "용어 추가"
	L["Term_Empty"] = "필터링된 용어가 없습니다."
	L["Term_Exists"] = "이미 존재하는 용어입니다: %s"
	L["Term_Added"] = "용어 추가됨: %s"
	L["Term_Removed"] = "용어 제거됨: %s"
	L["Terms"] = "용어"
	L["TermsList"] = "용어 목록"

	L["Verified"] = "확인됨"
	L["Addon"] = "애드온"
	L["Reported"] = "신고됨"
	L["GuildMute"] = "길드 음소거"
	L["CensusLeader"] = "인구 조사 지도자"
	L["CensusOfficer"] = "인구 조사 담당자"
	L["CensusTop"] = "인구 조사 상위"
	L["ChunkCensusReport"] = "청크 (인구 조사 보고서)"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "살펴보기"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "길드 초대"

	L["LeftChannel"] = "%s 채널을 나갔습니다."

return end

if LOCALE == "zhCN" then
	-- Simplified Chinese translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- 禁音
	L["TOC_Notes"] = "为游戏添加类似于增强版屏蔽系统的屏蔽功能。"
	L["SLASH_CHAT_MUTE1"] = "/禁音"
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/禁音列表"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "现在将屏蔽 %s。"
	L["Ignore_Removed"] = "不再屏蔽 %s。"
	L["Ignore_Added_Guild"] = "现在将屏蔽 <%s>。"
	L["Ignore_Removed_Guild"] = "不再屏蔽 <%s>。"
	L["MutePlayer"] = "屏蔽玩家"
	L["UnmutePlayer"] = "取消屏蔽玩家"
	L["MuteGuild"] = "屏蔽公会"
	L["UnmuteGuild"] = "取消屏蔽公会"
	L["Watcher"] = "观察者"
	L["NewEntry"] = "新条目 (%s)：%s [%s]%s"
	L["NewGuild"] = "新公会："
	L["MuteList"] = "屏蔽列表"
	L["MutedPlayers_Header"] = "已屏蔽玩家（%d）"
	L["MutedGuilds_Header"] = "已屏蔽公会（%d）"
	L["Watchlist_Header"] = "观察列表（%d）"
	L["ExceptedGuilds_Header"] = "排除的公会（%d）"
	L["MutedGuild"] = "已屏蔽公会"
	L["MutedViaGuild"] = "通过公会屏蔽：<%s>"
	L["UnmutedTheGuild"] = "（取消屏蔽也会取消对该公会的屏蔽）"
	L["ExceptedViaGuild"] = "<%s> 是已排除的公会"
	L["WatcherEntry"] = "观察条目（%s）"
	L["GuildEntry"] = "公会：<%s>"
	L["SeenCount"] = "已发现 %s 次"
	L["LastSeen"] = "最后发现：%s"
	L["MutedManually"] = "手动屏蔽"
	L["EnterEntryText"] = "输入要屏蔽的玩家或公会名称。\n或\n在聊天窗口中按住 Shift 点击名称"
	L["NoMutedPlayers"] = "没有已屏蔽的玩家。"
	L["HoldShiftToConfirm"] = "按住 Shift 键确认"
	L["ListeningOnChannel"] = "正在监听频道 #%s（%s）"
	L["CouldntJoin"] = "无法加入 %s（已设置密码、被封禁或频道名称已封存）"
	L["Verified"] = "已验证"
	L["Addon"] = "插件"
	L["Reported"] = "已举报"
	L["Suspected"] = "疑似"
	L["Exception"] = "例外（不屏蔽）"
	L["WatcherGuild"] = "观察中的公会"
	L["ExceptedGuild"] = "已排除的公会"
	L["SeenPlayersNumber"] = "已发现 %d 名玩家"
	L["PlayerIsMuted"] = "玩家已被屏蔽"
	L["Guild_Exception_Added"] = "已添加公会例外：%s"
	L["Guild_Exception_Removed"] = "已移除公会例外：%s"

	L["Setting_MuterHeader"] = "屏蔽"
	L["Setting_AddContextMenu"] = "添加屏蔽右键菜单"
	L["Setting_AddContextMenuTT"] = "将“屏蔽 / 取消屏蔽”添加到玩家的右键菜单中。"
	L["Setting_SpeechBubbles"] = "影响聊天气泡"
	L["Setting_SpeechBubblesTT"] = "切换是否混淆已屏蔽角色的聊天气泡文本。"
	L["Setting_Chat_Notify"] = "聊天通知"
	L["Setting_Chat_NotifyTT"] = "当观察者收集到新条目时，在聊天中显示消息。"
	L["Setting_PauseWatcher"] = "暂停观察者"
	L["Setting_PauseWatcherTT"] = "暂停收集新条目。已经收集的条目仍会保持屏蔽。"
	L["Setting_UseNetwork"] = "使用频道网络"
	L["Setting_UseNetworkTT"] = "利用 OlympusNet 频道为观察者收集屏蔽列表。\n仍会通过鼠标指向、/who 信息、姓名板和其他单位来源收集屏蔽对象。"

	L["Term_Contains"] = "包含"
	L["Term_ContainsTT"] = "只要消息中的任意位置出现匹配即可，即使位于其他单词内部。\"gold\" 也会匹配 \"golden\"。"
	L["Term_Word"] = "单词"
	L["Term_WordTT"] = "仅当该词作为独立单词出现时匹配。\"gold\" 会匹配 \"selling gold\"，但不会匹配 \"golden\"。"
	L["Term_ContainsAll"] = "包含全部"
	L["Term_ContainsAllTT"] = "仅当消息包含所有指定词条时匹配（以逗号分隔）。"
	L["Term_Advanced"] = "高级"
	L["Term_AdvancedTT"] = "使用 WoW Lua 的高级正则表达式 / 字符串模式进行匹配。"
	L["Term_Blocked"] = "已屏蔽消息：%d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "请输入至少一个词条。"
	L["Term_Help"] = "包含这些词条的消息将被隐藏。使用 , 分隔词条（例如：gold, wts）。不区分大小写。"
	L["Term_MatchType"] = "匹配类型"
	L["Term_EditTitle"] = "编辑词条"
	L["Term_AddTitle"] = "添加词条"
	L["Term_Empty"] = "没有已过滤的词条。"
	L["Term_Exists"] = "词条已存在：%s"
	L["Term_Added"] = "已添加词条：%s"
	L["Term_Removed"] = "已移除词条：%s"
	L["Terms"] = "词条"
	L["TermsList"] = "词条列表"

	L["Verified"] = "已验证"
	L["Addon"] = "插件"
	L["Reported"] = "已举报"
	L["GuildMute"] = "公会屏蔽"
	L["CensusLeader"] = "普查领导者"
	L["CensusOfficer"] = "普查官员"
	L["CensusTop"] = "普查顶级"
	L["ChunkCensusReport"] = "区块（普查报告）"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "查看"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "公会邀请"

	L["LeftChannel"] = "已离开频道 %s。"

return end

if LOCALE == "zhTW" then
	-- Traditional Chinese translations go here
	L["MUTE"] = MUTE
	L["TOC_Title"] = MUTE -- 消音
	L["TOC_Notes"] = "為遊戲新增類似於擴充版封鎖系統的封鎖功能。"
	L["SLASH_CHAT_MUTE1"] = "/消音"
	L["SLASH_CHAT_MUTE4"] = "/mute"
	L["MuteSlashHelp"] = L["SLASH_CHAT_MUTE1"] .." ".. CALENDAR_PLAYER_NAME
	L["SLASH_CHAT_MUTELIST1"] = "/消音列表"
	L["SLASH_CHAT_MUTELIST2"] = "/mutelist"
	L["Ignore_Added"] = "現在將會封鎖 %s。"
	L["Ignore_Removed"] = "不再封鎖 %s。"
	L["Ignore_Added_Guild"] = "現在將會封鎖 <%s>。"
	L["Ignore_Removed_Guild"] = "不再封鎖 <%s>。"
	L["MutePlayer"] = "封鎖玩家"
	L["UnmutePlayer"] = "取消封鎖玩家"
	L["MuteGuild"] = "封鎖公會"
	L["UnmuteGuild"] = "取消封鎖公會"
	L["Watcher"] = "觀察者"
	L["NewEntry"] = "新項目 (%s)：%s [%s]%s"
	L["NewGuild"] = "新公會："
	L["MuteList"] = "封鎖清單"
	L["MutedPlayers_Header"] = "已封鎖的玩家（%d）"
	L["MutedGuilds_Header"] = "已封鎖的公會（%d）"
	L["Watchlist_Header"] = "觀察名單（%d）"
	L["ExceptedGuilds_Header"] = "排除的公會（%d）"
	L["MutedGuild"] = "已封鎖的公會"
	L["MutedViaGuild"] = "透過公會封鎖：<%s>"
	L["UnmutedTheGuild"] = "（取消封鎖也會取消對該公會的封鎖）"
	L["ExceptedViaGuild"] = "<%s> 是已排除的公會"
	L["WatcherEntry"] = "觀察項目（%s）"
	L["GuildEntry"] = "公會：<%s>"
	L["SeenCount"] = "已發現 %s 次"
	L["LastSeen"] = "最後發現：%s"
	L["MutedManually"] = "手動封鎖"
	L["EnterEntryText"] = "輸入要封鎖的玩家或公會名稱。\n或\n在聊天視窗中按住 Shift 點擊名稱"
	L["NoMutedPlayers"] = "沒有已封鎖的玩家。"
	L["HoldShiftToConfirm"] = "按住 Shift 鍵確認"
	L["ListeningOnChannel"] = "正在監聽頻道 #%s（%s）"
	L["CouldntJoin"] = "無法加入 %s（已設定密碼、遭到封鎖或頻道名稱已封存）"
	L["Verified"] = "已驗證"
	L["Addon"] = "插件"
	L["Reported"] = "已檢舉"
	L["Suspected"] = "疑似"
	L["Exception"] = "例外（不封鎖）"
	L["WatcherGuild"] = "觀察中的公會"
	L["ExceptedGuild"] = "已排除的公會"
	L["SeenPlayersNumber"] = "已發現 %d 名玩家"
	L["PlayerIsMuted"] = "玩家已被封鎖"
	L["Guild_Exception_Added"] = "已新增公會例外：%s"
	L["Guild_Exception_Removed"] = "已移除公會例外：%s"

	L["Setting_MuterHeader"] = "封鎖"
	L["Setting_AddContextMenu"] = "新增封鎖右鍵選單"
	L["Setting_AddContextMenuTT"] = "將「封鎖 / 取消封鎖」新增至玩家的右鍵選單。"
	L["Setting_SpeechBubbles"] = "影響聊天泡泡"
	L["Setting_SpeechBubblesTT"] = "切換是否混淆已封鎖角色的聊天泡泡文字。"
	L["Setting_Chat_Notify"] = "聊天通知"
	L["Setting_Chat_NotifyTT"] = "當觀察者收集到新項目時，在聊天中顯示訊息。"
	L["Setting_PauseWatcher"] = "暫停觀察者"
	L["Setting_PauseWatcherTT"] = "暫停收集新項目。已收集的項目仍會保持封鎖。"
	L["Setting_UseNetwork"] = "使用頻道網路"
	L["Setting_UseNetworkTT"] = "利用 OlympusNet 頻道為觀察者收集封鎖名單。\n仍會透過滑鼠指向、/who 資訊、姓名板和其他單位來源收集封鎖對象。"

	L["Term_Contains"] = "包含"
	L["Term_ContainsTT"] = "只要訊息中的任意位置出現匹配即可，即使位於其他單字內。「gold」也會匹配「golden」。"
	L["Term_Word"] = "單字"
	L["Term_WordTT"] = "僅當該詞作為獨立單字出現時才會匹配。「gold」會匹配「selling gold」，但不會匹配「golden」。"
	L["Term_ContainsAll"] = "包含全部"
	L["Term_ContainsAllTT"] = "僅當訊息包含所有指定詞條時才會匹配（以逗號分隔）。"
	L["Term_Advanced"] = "進階"
	L["Term_AdvancedTT"] = "使用 WoW Lua 的進階正規表示式／字串模式進行匹配。"
	L["Term_Blocked"] = "已封鎖訊息：%d"
	L["Disabled"] = VIDEO_OPTIONS_DISABLED
	L["Enabled"] = VIDEO_OPTIONS_ENABLED
	L["Term_Invalid"] = "請至少輸入一個詞條。"
	L["Term_Help"] = "包含這些詞條的訊息會被隱藏。使用 , 分隔詞條（例如：gold, wts）。不區分大小寫。"
	L["Term_MatchType"] = "匹配類型"
	L["Term_EditTitle"] = "編輯詞條"
	L["Term_AddTitle"] = "新增詞條"
	L["Term_Empty"] = "沒有已篩選的詞條。"
	L["Term_Exists"] = "詞條已存在：%s"
	L["Term_Added"] = "已新增詞條：%s"
	L["Term_Removed"] = "已移除詞條：%s"
	L["Terms"] = "詞條"
	L["TermsList"] = "詞條清單"

	L["Verified"] = "已驗證"
	L["Addon"] = "插件"
	L["Reported"] = "已檢舉"
	L["GuildMute"] = "公會封鎖"
	L["CensusLeader"] = "普查領導者"
	L["CensusOfficer"] = "普查官員"
	L["CensusTop"] = "普查頂級"
	L["ChunkCensusReport"] = "區塊（普查報告）"
	L["OlympusNetAddon"] = "OlympusNet"
	L["Inspect"] = "檢視"
	L["ManualWho"] = "/who"
	L["GuildInvite"] = "公會邀請"

	L["LeftChannel"] = "已離開頻道 %s。"

return end